title: Youngrock Oh
position: Research Engineer
affiliation: AI Vision Lab, Samsung SDS
email: yrock.oh@gmail.com
keywords: 
google_scholar: https://scholar.google.com/
github_link: #https://github.com/yaoyao-liu/minimal-light
linkedin: #https://www.linkedin.com/
avatar: ./assets/img/202004_jeju_1_cr.jpg #./assets/img/avatar.png
google_analytics: #UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
